services:
  - type: web
    name: bookstore
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    # startCommand: "gunicorn --chdir bookstore bookstore.wsgi:application"
    disks:
      - name: media
        mountPath: /opt/render/project/bookstore/media
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: bookstore.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
