# Generated by Django 5.2.3 on 2025-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
