# Generated by Django 5.2.3 on 2025-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_books_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='genre',
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.TextField(blank=True, help_text='Comma-separated list of genres', null=True),
        ),
    ]
